- name: Update package manager cache (Debian)
  apt:
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Update package manager cache (RHEL/CentOS)
  yum:
    name: '*'
    state: latest
  when: ansible_os_family == "RedHat"

- name: Install Nginx (Debian)
  apt:
    name: nginx
    state: present
  when: ansible_os_family == "Debian"

- name: Install Nginx (RHEL/CentOS)
  yum:
    name: nginx
    state: present
  when: ansible_os_family == "RedHat"

- name: Start Nginx
  service:
    name: nginx
    state: started
    enabled: yes